### ISSUE TITLE
Achievements 

### ISSUE THREAD

**Issue by Meszaros91** [probablyraging/steam-game-idler#19] opened 2024-09-03 01:38 UTC
### Describe the issue

#1 after your lafest update i needed to go to %appdata% and delete the file or else the app would be off screen and no way to get back even uninstalling and reinstalling failled untill delete appdata folder and reboot the SGI

#2 since the update it does not detect how much achievements left (ex: Rust i have 70 of 93 achievements ... before idler would say 23 left farming .... niw it says 93 left ) and i am worried to run it as maybe it will rewrite the dates on existing achievements from years ago let me know if this is the case thanks ?

#3 bug or maybe not
 while achievement unlocker is running  we cannot select games to idle while farming achievements 

Solution? Maybe add a a list of games to run while runing achievement unlocker ...pre-selected before you start achievement unlocker or make it so you can start games or idle games while achievement unlocker running ? Idk 

#4 question i have not found a way to run 2 accounts unless i emulate 2 vmwares 

The program for me was running quite good after the time set from my suggestion. 

Hope this helps 

Thanks

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

**Comment by probablyraging** [comment] 2024-09-03 03:14
Thanks for reporting these issues mate. I did just release `v1.5.0` which has quite a few major updates, so no surprise there are a few issues, sorry about that.

1. This is likely due to the introduction of storing the window state in `v1.4.5`, and likely shouldn't be an issue going forward if you've managed to solve it. A simple fix may have been to hold WINKEY and press left/right arrow key to cycle it through the positions on your desktop, usually does the job for me when a window in a weird position.

2. Good catch, this is now fixed in `v1.5.2` with https://github.com/probablyraging/steam-game-idler/commit/25cb6591918fb74d8d3b639fb8e04eb094b3b3ed. This wouldn't have caused an issue in terms of locking already unlocked achievements, they would have still be skipped, the issue was that it wasn't correctly filtering them out initially.

3. This is not a bug. If you would like to do other tasks while the `achievement unlocker` feature is running, you can open a second instance of SGI to idle games, farm cards, or even run the `achievement unlocker` on another game. I likely won't add the feature you mentioned, as opening a second instance seems easy enough, but thank you for the suggestion.

4. SGI uses legitimate methods to interact with the Steam client via Steamworks API. Similar to when you actually play a game via Steam, you can't run multiple instances of Steam on a single PC, and you can't run multiple instances of a game while that game is already running on the same or another PC. Your only real option here is to use multiple VMs as you already are, or switch between accounts when you need to.

Thanks again for the reports and suggestions!

**Closed by probablyraging** 2024-09-03 03:14 UTC
Labels: bug, investigating
