### ISSUE TITLE
Achievement Unlocker getting Stuck in Loading Screen

### ISSUE THREAD

**Issue by killerboyyy777** [probablyraging/steam-game-idler#26] opened 2024-09-07 00:28 UTC
### Describe the issue

When i start Acievement Unlocker, it gets stuck in a Screen saying 
"Unlocking 0 achievement(s) for" "This may take a minute"
even after multiple Hours of waiting it still is stuck.
Logs give those Errors:
[v1.5.12] [Error] in (fetchAchievements) TypeError: Cannot read properties of undefined (reading 'toString')
[v1.5.12] [Error] in (startAchievementUnlocker) TypeError: Cannot read properties of undefined (reading 'appid')
[v1.5.12] [Error] in (stopIdler) util: TypeError: Cannot read properties of undefined (reading 'toString')

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

**Comment by probablyraging** [comment] 2024-09-07 01:10
Thanks for the issue report.

Would you mind letting me know which game you are trying to unlock achievements for and would you also be able to upload your `log.txt` file from `C:\Users\<user>\AppData\Roaming\steam-game-idler`

Thanks

**Comment by killerboyyy777** [comment] 2024-09-07 01:13
[log.txt](https://github.com/user-attachments/files/16913899/log.txt)
there are a bunch of games in there, and it worked previously. stopped working 2 or 3 updates ago but just decided to report it now

**Comment by probablyraging** [comment] 2024-09-07 01:21
Thanks for that.

Make note of the games in your `favorites`, `card idler`, and `achievement unlocker` lists if you need to, as this method will clear them, then try the following steps:
1. Go to `settings > general` and enable `Delete locally saved data on logout`
2. Log out of SGI
3. Add your games back to the `achievement unlocker` list and try running it again

Let me know if that works for you

**Comment by killerboyyy777** [comment] 2024-09-07 01:25
yeah, works again. thanks

**Comment by probablyraging** [comment] 2024-09-07 01:31
Glad to hear it, thanks again for the report.

Just to note this issue before closing it. This is caused by the `1.5.0` update, as the naming convention in the data returned by the new endpoint changed from `game.appId` to `game.appid` _(lower case `i`)_. Games added to lists prior to that update were stored with the old property name, which caused the error.

**Closed by probablyraging** 2024-09-07 01:31 UTC
Labels: bug, investigating
